version: '3.8'

services:
  # MySQL Service - Dành cho User, Role, Employee (Dữ liệu quan hệ)
  mysql_db:
    image: mysql:8.0
    container_name: ec_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'english_center_db'
      MYSQL_ROOT_PASSWORD: 'root123456' # Đổi pass này khi deploy prod
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ec_network

  # MongoDB Service - Dành cho dữ liệu động (Học sinh, Điểm số sau này)
  mongo_db:
    image: mongo:latest
    container_name: ec_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin123456'
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ec_network

  # (Optional) Mongo Express - Giao diện web để xem dữ liệu MongoDB nhanh
  mongo-express:
    image: mongo-express
    container_name: ec_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin_password@mongo_db:27017/
    networks:
      - ec_network
    depends_on:
      - mongo_db

volumes:
  mysql_data:
  mongo_data:

networks:
  ec_network:
    driver: bridge